### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by mpbl** [vivek-bala/radical.entk-0.6#16]
Vivek,

I was trying to run your example and had some trouble doing so:

https://github.com/vivek-bala/radical.entk/blob/0bf075dbdddaaa5c7a23934c71d0140ad5bc1d8a/src/radical/entk/execman/resource_manager.py#L252

Shouldn't ```database_url``` be``` dburl``` ?

**Comment by vivek-bala** [comment]
Hey @mpbl , yes I changed it to dburl now. I was testing against different versions of RP and I think I missed pushing this change. Thanks, please test and feel free to close the ticket if it is resolved.

**Comment by vivek-bala** [comment]
This has been addressed in devel.
