### ISSUE TITLE
EnTK fails on (apparently) the input data staging phase. 

### ISSUE THREAD

**Issue by SrinivasMushnoori** [vivek-bala/radical.entk-0.6#25]
Running a job on Comet using EnTK 0.6. 
Fails, and upon inspecting the units on the Comet RP sandbox, only three of the five required input files have been staged. What further information is needed from me to diagnose this?

Will gladly help debug.

**Comment by vivek-bala** [comment]
This is resolved. It was due to a type in the main script.
